# Generated by Django 4.1 on 2023-08-25 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_remove_user_first_name_remove_user_last_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('user', 'normal_user'), ('super_user', 'super_user')], default='user', max_length=20),
        ),
    ]
