# Generated by Django 4.1 on 2023-08-26 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_alter_user_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('user', 'normal_user'), ('admin', 'admin'), ('super_user', 'super_user')], default='user', max_length=20),
        ),
    ]
