# Generated by Django 4.1 on 2023-10-04 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Instruction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='title')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('img', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Image')),
                ('time', models.SmallIntegerField(default=0, verbose_name='Time')),
                ('difficulty', models.CharField(choices=[('easy', 'آسان'), ('moderate', 'متوسط'), ('hard', 'سخت')], max_length=20, verbose_name='Difficulty')),
            ],
        ),
    ]
