# Generated by Django 4.1 on 2023-10-04 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instruction', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instruction',
            name='difficulty',
            field=models.CharField(choices=[('easy', 'آسان'), ('moderate', 'متوسط'), ('hard', 'سخت')], default='آسان', max_length=20, verbose_name='Difficulty'),
        ),
    ]
