# Generated by Django 4.1 on 2023-10-04 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instruction', '0002_alter_instruction_difficulty'),
    ]

    operations = [
        migrations.AddField(
            model_name='instruction',
            name='ingredients',
            field=models.TextField(blank=True, null=True, verbose_name='Ingredients'),
        ),
        migrations.AddField(
            model_name='instruction',
            name='recipe',
            field=models.TextField(blank=True, null=True, verbose_name='Recipe'),
        ),
        migrations.AlterField(
            model_name='instruction',
            name='difficulty',
            field=models.CharField(choices=[('آسان', 'آسان'), ('متوسط', 'متوسط'), ('سخت', 'سخت')], default='آسان', max_length=20, verbose_name='Difficulty'),
        ),
    ]
