# Generated by Django 4.1 on 2023-08-25 18:18

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(max_length=400, upload_to=core.models.upload_image_src)),
            ],
            options={
                'ordering': ('-id',),
            },
        ),
    ]
