# Generated by Django 4.1 on 2023-08-25 18:21

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customproduct',
            name='detail',
            field=jsonfield.fields.JSONField(default={}),
            preserve_default=False,
        ),
    ]
