# Generated by Django 4.1 on 2023-09-18 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customorderproduct',
            name='status',
            field=models.CharField(choices=[('accepted', 'تایید شد'), ('pending', 'در حال بررسی'), ('rejected', 'رد شد')], default='pending', max_length=15),
        ),
    ]
