# Generated by Django 4.1 on 2023-08-25 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_customproduct_detail'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CustomProduct',
            new_name='CustomOrderProduct',
        ),
    ]
