# Generated by Django 4.1 on 2023-08-30 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_factor_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShowCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('products', models.ManyToManyField(to='product.product')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
