# Generated by Django 4.1 on 2023-08-25 20:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_image'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('product', '0003_rename_customproduct_customorderproduct'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customorderproduct',
            options={'ordering': ('-id',)},
        ),
        migrations.RemoveField(
            model_name='customorderproduct',
            name='date_receive',
        ),
        migrations.RemoveField(
            model_name='customorderproduct',
            name='time_receive',
        ),
        migrations.RemoveField(
            model_name='customorderproduct',
            name='type_product',
        ),
        migrations.AddField(
            model_name='customorderproduct',
            name='images',
            field=models.ManyToManyField(to='core.image'),
        ),
        migrations.AddField(
            model_name='customorderproduct',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customorderproduct',
            name='note',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='customorderproduct',
            name='price',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='customorderproduct',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
