# Generated by Django 4.1 on 2023-10-23 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_candy_candybox_boxrow'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pakage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200, verbose_name='Name')),
                ('price', models.IntegerField(default=0, verbose_name='Price')),
                ('balloon', models.BooleanField(default=False)),
                ('candle', models.BooleanField(default=False)),
                ('thread', models.BooleanField(default=False)),
                ('dish', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
