# Generated by Django 4.1 on 2023-08-25 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_alter_customorderproduct_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customorderproduct',
            name='is_checked',
            field=models.BooleanField(default=False),
        ),
    ]
