# Generated by Django 4.1 on 2023-08-30 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_cart_discount_order_payment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customorderproduct',
            name='price',
            field=models.PositiveBigIntegerField(default=0),
        ),
    ]
