# Generated by Django 4.1 on 2023-11-17 18:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_alter_pakage_options_pakage_images'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candybox',
            name='user',
        ),
        migrations.RemoveField(
            model_name='pakage',
            name='images',
        ),
        migrations.AddField(
            model_name='factor',
            name='created_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='factor',
            name='modified_time',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.DeleteModel(
            name='BoxRow',
        ),
        migrations.DeleteModel(
            name='Candy',
        ),
        migrations.DeleteModel(
            name='CandyBox',
        ),
        migrations.DeleteModel(
            name='Pakage',
        ),
    ]
