# Generated by Django 4.1 on 2023-11-17 19:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_category_type_name'),
        ('product', '0006_remove_candybox_user_remove_pakage_images_and_more'),
    ]

    operations = [
    ]
