# Generated by Django 4.1 on 2023-09-01 04:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transportation', '0001_initial'),
        ('product', '0006_rename_payment_factor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='factor',
            old_name='description',
            new_name='detail',
        ),
        migrations.RemoveField(
            model_name='factor',
            name='price_paid',
        ),
        migrations.AddField(
            model_name='factor',
            name='address',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='transportation.address'),
        ),
        migrations.AddField(
            model_name='factor',
            name='delivery_type',
            field=models.CharField(choices=[('online', 'online'), ('in-person', 'in-person')], default='online', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='factor',
            name='note',
            field=models.TextField(null=True),
        ),
        migrations.CreateModel(
            name='FactorPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('track_code', models.CharField(max_length=30)),
                ('detail', models.TextField(null=True)),
                ('price_paid', models.PositiveBigIntegerField()),
                ('factor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='product.factor')),
            ],
            options={
                'ordering': ('-id',),
            },
        ),
    ]
