# Generated by Django 4.1 on 2023-09-01 05:14

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_rename_description_factor_detail_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factor',
            name='detail',
            field=jsonfield.fields.JSONField(default={}),
            preserve_default=False,
        ),
    ]
