# Generated by Django 4.1 on 2023-09-01 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_alter_factor_detail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='factorpayment',
            name='track_code',
        ),
        migrations.AddField(
            model_name='factorpayment',
            name='authority',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
    ]
