# Generated by Django 4.1 on 2023-08-26 20:34

import core.utils
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_alter_product_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Factor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('track_code', models.CharField(default=core.utils.random_str, max_length=20)),
                ('price_paid', models.PositiveBigIntegerField()),
            ],
            options={
                'ordering': ('-id',),
            },
        ),
        migrations.RemoveField(
            model_name='customorderproduct',
            name='is_paid',
        ),
        migrations.AddField(
            model_name='customorderproduct',
            name='factor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='product.factor'),
        ),
    ]
