# Generated by Django 4.1 on 2023-08-26 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_factor_remove_customorderproduct_is_paid_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customorderproduct',
            name='price',
        ),
        migrations.AddField(
            model_name='factor',
            name='price',
            field=models.PositiveBigIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='factor',
            name='price_paid',
            field=models.PositiveBigIntegerField(default=0),
        ),
    ]
