# Generated by Django 4.1 on 2023-12-04 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_category_type_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='type_name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
