# Generated by Django 4.1 on 2023-09-02 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_remove_factorpayment_track_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='factor',
            name='process_to_payment',
            field=models.BooleanField(default=False),
        ),
    ]
