# Generated by Django 4.1 on 2023-08-26 21:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0010_remove_customorderproduct_price_factor_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customorderproduct',
            name='factor',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='product.factor'),
        ),
    ]
