# Generated by Django 4.1 on 2023-12-11 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0010_alter_category_type_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartstatus',
            name='delivery_time',
            field=models.CharField(default='-', max_length=20),
            preserve_default=False,
        ),
    ]
