# Generated by Django 4.1 on 2023-12-11 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0011_alter_cartstatus_delivery_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='boxrow',
            name='_is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='candy',
            name='_is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='candybox',
            name='_is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='cart',
            name='_is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='cartstatus',
            name='_is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='category',
            name='_is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='comment',
            name='_is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customorderproduct',
            name='_is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='discount',
            name='_is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='factor',
            name='_is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='factorcakeimage',
            name='_is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='factorpayment',
            name='_is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='_is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pakage',
            name='_is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='_is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='productfavoritelist',
            name='_is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='showcase',
            name='_is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
