# Generated by Django 4.1 on 2023-08-27 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0012_factorcakeimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='factorcakeimage',
            name='is_checked',
            field=models.BooleanField(default=False),
        ),
    ]
