# Generated by Django 4.1 on 2023-09-03 21:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0012_alter_cart_discount'),
    ]

    operations = [
        migrations.CreateModel(
            name='CartStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('checking', 'در حال بررسی'), ('accepted', 'تایید'), ('send', 'خروج از مرکز سفارش'), ('delivered', 'تحویل به مشتری')], max_length=20)),
                ('delivery_time', models.IntegerField(null=True)),
                ('cart', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='product.cart')),
            ],
            options={
                'ordering': ('-id',),
            },
        ),
    ]
