# Generated by Django 4.1 on 2023-12-11 05:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0013_cartmanualpayment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartmanualpayment',
            name='cart',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.cart'),
        ),
    ]
