# Generated by Django 4.1 on 2023-09-03 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0014_alter_cartstatus_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='factor',
            name='shipping_fee',
            field=models.PositiveBigIntegerField(default=0),
        ),
    ]
