# Generated by Django 4.1 on 2023-12-11 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transportation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='_is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='mapaddress',
            name='_is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
